apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/test-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
